import { expect, test } from '../fixtures';

const realDatabaseE2e = process.env['MYADMIN_REAL_DATABASE_E2E'] === '1';
const admin = { username: 'browser-admin', password: 'synthetic-browser-password' };

test.skip(!realDatabaseE2e, 'Set MYADMIN_REAL_DATABASE_E2E=1 to run against disposable engines.');

test('E2E-0038-AC5 and E2E-0038-AC9 edit JSON and preserve explicit NULL on both engines', async ({
  page,
}) => {
  test.setTimeout(180_000);
  const setupStatus = await page.request.get('/api/v1/setup/status');
  expect(setupStatus.ok()).toBe(true);
  if (!((await setupStatus.json()) as { initialized: boolean }).initialized) {
    expect((await page.request.post('/api/v1/setup/admin', { data: admin })).status()).toBe(201);
  }

  await page.goto('/login');
  await page.getByLabel('Username').fill(admin.username);
  await page.getByLabel('Password').fill(admin.password);
  await page.getByLabel('Password').press('Enter');
  await expect(page).toHaveURL(/\/workspace$/);

  const csrf = { 'x-myadmin-csrf': '1' };
  const runId = crypto.randomUUID().replaceAll('-', '').slice(0, 10);
  const targets = [
    {
      engine: 'postgresql' as const,
      port: 55433,
      database: 'myadmin_test',
      schema: 'public',
      user: 'myadmin_test',
      secret: 'myadmin_test_password',
    },
    {
      engine: 'mysql' as const,
      port: 3380,
      database: 'fixture',
      schema: null,
      user: 'root',
      secret: 'myadmin-test-root',
    },
  ];

  for (const target of targets) {
    const connection = await page.request.post('/api/v1/connections', {
      data: {
        label: `typed_e2e_${target.engine}_${runId}`,
        engine: target.engine,
        host: '127.0.0.1',
        port: target.port,
        database: target.database,
        username: target.user,
        sslMode: target.engine === 'postgresql' ? 'disable' : 'require',
        tlsOptions: null,
        connectTimeoutMs: 5_000,
        groupId: null,
        tag: 'typed-e2e',
        color: null,
        secret: target.secret,
        saveSecret: true,
      },
      headers: csrf,
    });
    expect(connection.status()).toBe(201);
    const connectionId = ((await connection.json()) as { id: string }).id;
    const table = `typed_e2e_${target.engine === 'postgresql' ? 'pg' : 'my'}_${runId}`;
    const ref = {
      database: target.database,
      schema: target.schema,
      name: table,
      type: 'table' as const,
    };
    const quote = target.engine === 'postgresql' ? `"${table}"` : `\`${table}\``;
    const payloadType = target.engine === 'postgresql' ? 'jsonb' : 'JSON';

    try {
      expect(
        (
          await page.request.post(`/api/v1/connections/${connectionId}/connect`, {
            data: { secret: target.secret },
            headers: csrf,
          })
        ).status(),
      ).toBe(200);
      const setup = await page.request.post('/api/v1/query/executions', {
        data: {
          connectionId,
          database: target.database,
          schema: target.schema ?? target.database,
          sql: `CREATE TABLE ${quote} (id integer ${target.engine === 'postgresql' ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTO_INCREMENT'} PRIMARY KEY, payload ${payloadType} NOT NULL, note varchar(80) NULL); INSERT INTO ${quote} (payload, note) VALUES ('{"seed":true}', NULL);`,
          mode: 'full',
          tabSessionId: `typed-${target.engine}-${runId}`,
        },
        headers: csrf,
      });
      const setupBody = await setup.text();
      expect(setup.status(), setupBody).toBe(202);
      const executionId = (JSON.parse(setupBody) as { executionId: string }).executionId;
      for (let attempt = 0; attempt < 100; attempt += 1) {
        const current = await page.request.get(`/api/v1/query/executions/${executionId}`);
        expect(current.ok()).toBe(true);
        const state = (await current.json()) as { state: string };
        if (state.state === 'completed') break;
        expect(['queued', 'running']).toContain(state.state);
        await new Promise((resolve) => setTimeout(resolve, 100));
        if (attempt === 99) throw new Error(`Typed ${target.engine} setup did not complete`);
      }

      await page.goto(
        `/data-browser?connection=${encodeURIComponent(connectionId)}&ref=${encodeURIComponent(JSON.stringify(ref))}`,
      );
      await expect(page.getByRole('grid')).toBeVisible();
      const payloadCell = page.getByRole('gridcell').filter({ hasText: 'seed' }).first();
      await expect(payloadCell).toBeVisible();
      await payloadCell.dblclick();
      const jsonDialog = page.getByRole('dialog', { name: 'Edit payload' });
      await expect(jsonDialog).toBeVisible();
      await jsonDialog.getByLabel('JSON value').fill('{"seed":true,"engine":"updated"}');
      const jsonUpdate = page.waitForResponse(
        (response) =>
          response.url().includes('/api/v1/data/rows') && response.request().method() === 'PATCH',
      );
      await jsonDialog.getByRole('button', { name: 'Save cell' }).click();
      expect((await jsonUpdate).status()).toBe(200);
      await expect(page.getByRole('gridcell').filter({ hasText: 'updated' }).first()).toBeVisible();

      const nullCell = page.getByRole('gridcell', { name: 'note: NULL' });
      await nullCell.dblclick();
      const nullDialog = page.getByRole('dialog', { name: 'Edit note' });
      await expect(nullDialog).toBeVisible();
      await nullDialog.getByLabel('Cell value').fill('temporary value');
      await nullDialog.getByText('Set NULL explicitly').click();
      const nullUpdate = page.waitForResponse(
        (response) =>
          response.url().includes('/api/v1/data/rows') && response.request().method() === 'PATCH',
      );
      await nullDialog.getByRole('button', { name: 'Save cell' }).click();
      expect((await nullUpdate).status()).toBe(200);
      await expect(page.getByRole('gridcell', { name: 'note: NULL' })).toBeVisible();
      const staleCell = await page.getByRole('gridcell', { name: 'note: NULL' }).elementHandle();
      expect(staleCell).not.toBeNull();

      const externalDelete = await page.request.post('/api/v1/data/rows/delete', {
        data: { connectionId, ref, identities: [{ id: { type: 'number', value: '1' } }] },
        headers: csrf,
      });
      expect(externalDelete.status()).toBe(200);
      await staleCell!.dblclick();
      const conflictDialog = page.getByRole('dialog', { name: 'Edit note' });
      await expect(conflictDialog).toBeVisible();
      await conflictDialog.getByLabel('Cell value').fill('stale write');
      const conflictResponse = page.waitForResponse(
        (response) =>
          response.url().includes('/api/v1/data/rows') && response.request().method() === 'PATCH',
      );
      await conflictDialog.getByRole('button', { name: 'Save cell' }).click();
      expect((await conflictResponse).status()).toBe(409);
      await expect(page.getByRole('alert')).toContainText('Reload the data');
    } finally {
      await page.request
        .delete('/api/v1/tables/drop', {
          data: { connectionId, ref, confirmName: table },
          headers: csrf,
        })
        .catch(() => undefined);
      await page.request
        .delete(`/api/v1/connections/${connectionId}`, { headers: csrf })
        .catch(() => undefined);
    }
  }
});
