import { expect, test } from '../fixtures';

const realDatabaseE2e = process.env['MYADMIN_REAL_DATABASE_E2E'] === '1';
const admin = { username: 'browser-admin', password: 'synthetic-browser-password' };

interface RealConnection {
  id: string;
  readonly label: string;
  readonly engine: 'postgresql' | 'mysql';
  readonly port: number;
  readonly database: string;
  readonly secret: string;
}

test.skip(!realDatabaseE2e, 'Set MYADMIN_REAL_DATABASE_E2E=1 to run against disposable engines.');

test('E2E-0031-AC8, E2E-0032-AC6, E2E-0033-AC8, E2E-0033-AC9, E2E-0035-AC1, E2E-0035-AC2, E2E-0035-AC5, E2E-0035-AC6, E2E-0035-AC7, E2E-0035-AC8, E2E-0037-AC1, E2E-0038-AC9, E2E-0039-AC1, E2E-0039-AC2, E2E-0039-AC3, E2E-0039-AC5, E2E-0039-AC6, E2E-0040-AC1, E2E-0040-AC3, E2E-0040-AC4, E2E-0040-AC6, E2E-0041-AC8, E2E-0043-AC1, E2E-0043-AC2, E2E-0043-AC5, and E2E-0043-AC6 execute real database workflows', async ({
  page,
}) => {
  test.setTimeout(300_000);
  const setupStatus = await page.request.get('/api/v1/setup/status');
  expect(setupStatus.ok()).toBe(true);
  if (!((await setupStatus.json()) as { initialized: boolean }).initialized) {
    const setup = await page.request.post('/api/v1/setup/admin', { data: admin });
    expect(setup.status()).toBe(201);
  }

  await page.goto('/login');
  await page.getByLabel('Username').fill(admin.username);
  await page.getByLabel('Password').fill(admin.password);
  await page.getByLabel('Password').press('Enter');
  await expect(page).toHaveURL(/\/workspace$/);

  const runLabel = crypto.randomUUID().replaceAll('-', '').slice(0, 8);
  const connections: RealConnection[] = [
    {
      id: '',
      label: `a_e2e_${runLabel}_PostgreSQL`,
      engine: 'postgresql',
      port: 55433,
      database: 'myadmin_test',
      secret: 'myadmin_test_password',
    },
    {
      id: '',
      label: `a_e2e_${runLabel}_MySQL`,
      engine: 'mysql',
      port: 3380,
      database: 'fixture',
      secret: 'myadmin-test-root',
    },
  ];
  const realTables = new Map<string, string>();
  const searchPrefixes = new Map<string, string>();
  for (const connection of connections) {
    const created = await page.request.post('/api/v1/connections', {
      data: {
        label: connection.label,
        engine: connection.engine,
        host: '127.0.0.1',
        port: connection.port,
        database: connection.database,
        username: connection.engine === 'postgresql' ? 'myadmin_test' : 'root',
        sslMode: connection.engine === 'postgresql' ? 'disable' : 'require',
        tlsOptions: null,
        connectTimeoutMs: 5_000,
        groupId: null,
        tag: 'e2e',
        color: null,
        secret: connection.engine === 'postgresql' ? connection.secret : 'myadmin-test-root',
        saveSecret: true,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(created.status()).toBe(201);
    const createdBody = (await created.json()) as { id: string };
    connection.id = createdBody.id;

    const connected = await page.request.post(`/api/v1/connections/${connection.id}/connect`, {
      data: { secret: connection.secret },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(connected.status()).toBe(200);

    const table = `e2e_${connection.engine === 'postgresql' ? 'pg' : 'my'}_${crypto.randomUUID().replaceAll('-', '').slice(0, 12)}`;
    const database = connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture';
    const schema = connection.engine === 'postgresql' ? 'public' : 'fixture';
    const sql =
      connection.engine === 'postgresql'
        ? `CREATE TABLE "${table}" (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(80) NOT NULL); INSERT INTO "${table}" (name) VALUES ('browser fixture');`
        : `CREATE TABLE \`${table}\` (id integer AUTO_INCREMENT PRIMARY KEY, name varchar(80) NOT NULL); INSERT INTO \`${table}\` (name) VALUES ('browser fixture');`;
    const execution = await page.request.post('/api/v1/query/executions', {
      data: {
        connectionId: connection.id,
        database,
        schema,
        sql,
        mode: 'full',
        tabSessionId: `setup-${connection.engine}`,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(execution.status()).toBe(202);
    const executionId = ((await execution.json()) as { executionId: string }).executionId;
    for (let attempt = 0; attempt < 50; attempt += 1) {
      const current = await page.request.get(`/api/v1/query/executions/${executionId}`);
      expect(current.ok()).toBe(true);
      const state = (await current.json()) as { state: string };
      if (state.state === 'completed') break;
      expect(['queued', 'running']).toContain(state.state);
      await new Promise((resolve) => setTimeout(resolve, 100));
      if (attempt === 49) throw new Error(`Real ${connection.engine} setup query did not complete`);
    }
    realTables.set(connection.id, table);

    // Keep this fixture before prior disposable runs in the catalog so the
    // reveal assertion exercises the first metadata page deterministically.
    const searchPrefix = `a_e2e_0000search_${connection.engine === 'postgresql' ? 'pg' : 'my'}_${crypto.randomUUID().replaceAll('-', '').slice(0, 8)}`;
    const searchSql = Array.from({ length: 2_000 }, (_, index) => {
      const name = `${searchPrefix}_${String(index).padStart(4, '0')}`;
      return connection.engine === 'postgresql'
        ? `CREATE TABLE "${name}" (id integer);`
        : `CREATE TABLE \`${name}\` (id integer);`;
    }).join('\n');
    const searchExecution = await page.request.post('/api/v1/query/executions', {
      data: {
        connectionId: connection.id,
        database,
        schema,
        sql: searchSql,
        mode: 'full',
        tabSessionId: `search-setup-${connection.engine}`,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(searchExecution.status()).toBe(202);
    const searchExecutionId = ((await searchExecution.json()) as { executionId: string })
      .executionId;
    for (let attempt = 0; attempt < 480; attempt += 1) {
      const current = await page.request.get(`/api/v1/query/executions/${searchExecutionId}`);
      expect(current.ok()).toBe(true);
      const state = (await current.json()) as { state: string };
      if (state.state === 'completed') break;
      expect(['queued', 'running']).toContain(state.state);
      await new Promise((resolve) => setTimeout(resolve, 250));
      if (attempt === 479)
        throw new Error(`Real ${connection.engine} search setup did not complete`);
    }
    searchPrefixes.set(connection.id, searchPrefix);
  }

  // Exercise the database management page against each real provider. The
  // created database is removed through the same page so a failed assertion
  // does not leave a disposable fixture behind when the request is available.
  for (const connection of connections) {
    const sourceDatabase = connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture';
    const createdDatabase = `e2e_db_${connection.engine}_${runLabel}`;
    try {
      await page.goto(
        `/database?connection=${encodeURIComponent(connection.id)}&database=${encodeURIComponent(sourceDatabase)}`,
      );
      await expect(page.getByRole('heading', { name: 'Database properties' })).toBeVisible();
      await expect(page.getByRole('heading', { name: sourceDatabase, exact: true })).toBeVisible();
      await page.getByRole('button', { name: 'Create database' }).click();
      const createDialog = page.getByRole('dialog', { name: 'Create database' });
      await expect(createDialog).toBeVisible();
      await createDialog.getByRole('textbox', { name: 'Name', exact: true }).fill(createdDatabase);
      const createResponse = page.waitForResponse(
        (response) =>
          response.url().includes(`/api/v1/connections/${connection.id}/databases`) &&
          response.request().method() === 'POST',
      );
      await createDialog.getByRole('button', { name: 'Create database', exact: true }).click();
      expect((await createResponse).status()).toBe(201);

      await page.goto(
        `/database?connection=${encodeURIComponent(connection.id)}&database=${encodeURIComponent(createdDatabase)}`,
      );
      await expect(page.getByRole('heading', { name: createdDatabase, exact: true })).toBeVisible();
      await page.getByRole('button', { name: 'Drop database' }).click();
      const dropDialog = page.getByRole('dialog');
      await expect(dropDialog).toBeVisible();
      await dropDialog.getByLabel('Database name confirmation').fill(createdDatabase);
      const dropResponse = page.waitForResponse(
        (response) =>
          response
            .url()
            .includes(`/api/v1/connections/${connection.id}/databases/${createdDatabase}`) &&
          response.request().method() === 'DELETE',
      );
      await dropDialog.getByRole('button', { name: 'Delete database', exact: true }).click();
      expect((await dropResponse).status()).toBe(204);
      await expect(page).toHaveURL(/\/explorer$/);
    } finally {
      // The UI path is the acceptance proof; this is only a safety cleanup for
      // failures before the destructive confirmation reaches the server.
      await page.request
        .delete(`/api/v1/connections/${connection.id}/databases/${createdDatabase}`, {
          data: { confirmName: createdDatabase },
          headers: { 'x-myadmin-csrf': '1' },
        })
        .catch(() => undefined);
    }
  }

  const postgresql = connections.find((connection) => connection.engine === 'postgresql');
  if (!postgresql) throw new Error('PostgreSQL disposable connection was not created');
  const schemaName = `e2e_schema_${runLabel}`;
  const renamedSchemaName = `${schemaName}_renamed`;
  try {
    await page.goto(
      `/schema?connection=${encodeURIComponent(postgresql.id)}&database=${encodeURIComponent(postgresql.database)}`,
    );
    await expect(page.getByRole('heading', { name: 'Schema management' })).toBeVisible();
    await page.getByRole('button', { name: 'Create schema' }).click();
    const createSchemaDialog = page.getByRole('dialog', { name: 'Create schema' });
    await createSchemaDialog.getByLabel('Name').fill(schemaName);
    const createSchemaResponse = page.waitForResponse(
      (response) =>
        response
          .url()
          .includes(
            `/api/v1/connections/${postgresql.id}/databases/${postgresql.database}/schemas`,
          ) && response.request().method() === 'POST',
    );
    await createSchemaDialog.getByRole('button', { name: 'Create schema', exact: true }).click();
    expect((await createSchemaResponse).status()).toBe(201);

    await page.reload();
    const createdSchema = page.getByRole('main').getByText(schemaName, { exact: true });
    await expect(createdSchema).toBeVisible();
    await createdSchema.locator('../..').getByRole('button', { name: 'Rename' }).click();
    const renameSchemaDialog = page.getByRole('dialog', { name: 'Rename schema' });
    await renameSchemaDialog.getByLabel('New name').fill(renamedSchemaName);
    const renameSchemaResponse = page.waitForResponse(
      (response) =>
        response
          .url()
          .includes(
            `/api/v1/connections/${postgresql.id}/databases/${postgresql.database}/schemas/`,
          ) && response.request().method() === 'PATCH',
    );
    await renameSchemaDialog.getByRole('button', { name: 'Rename schema', exact: true }).click();
    expect((await renameSchemaResponse).status()).toBe(200);

    await page.reload();
    const renamedSchema = page.getByRole('main').getByText(renamedSchemaName, { exact: true });
    await expect(renamedSchema).toBeVisible();
    await renamedSchema.locator('../..').getByRole('button', { name: 'Drop' }).click();
    const dropSchemaDialog = page.getByRole('dialog');
    await dropSchemaDialog.getByLabel('schema name confirmation').fill(renamedSchemaName);
    const dropSchemaResponse = page.waitForResponse(
      (response) =>
        response
          .url()
          .includes(
            `/api/v1/connections/${postgresql.id}/databases/${postgresql.database}/schemas/`,
          ) && response.request().method() === 'DELETE',
    );
    await dropSchemaDialog.getByRole('button', { name: 'Delete schema', exact: true }).click();
    expect((await dropSchemaResponse).status()).toBe(204);
  } finally {
    await page.request
      .delete(
        `/api/v1/connections/${postgresql.id}/databases/${postgresql.database}/schemas/${encodeURIComponent(renamedSchemaName)}`,
        {
          data: { confirmName: renamedSchemaName },
          headers: { 'x-myadmin-csrf': '1' },
        },
      )
      .catch(() => undefined);
    await page.request
      .delete(
        `/api/v1/connections/${postgresql.id}/databases/${postgresql.database}/schemas/${encodeURIComponent(schemaName)}`,
        {
          data: { confirmName: schemaName },
          headers: { 'x-myadmin-csrf': '1' },
        },
      )
      .catch(() => undefined);
  }

  const mysql = connections.find((connection) => connection.engine === 'mysql');
  if (!mysql) throw new Error('MySQL disposable connection was not created');
  const forcedSchemaRequest = await page.request.post(
    `/api/v1/connections/${mysql.id}/databases/${encodeURIComponent(mysql.database)}/schemas`,
    {
      data: { name: `forced_schema_${runLabel}` },
      headers: { 'x-myadmin-csrf': '1' },
    },
  );
  expect(forcedSchemaRequest.status()).toBe(501);
  await expect(forcedSchemaRequest.json()).resolves.toMatchObject({
    code: 'SCHEMA_UNSUPPORTED',
  });

  await page.goto('/query-editor');
  await expect(page.getByRole('heading', { name: 'SQL editor' })).toBeVisible();

  for (const connection of connections) {
    await page.getByLabel('Connection').selectOption(connection.id);
    await expect(page.getByText(connection.engine, { exact: true })).toBeVisible();
    // The result panel can overlap the sticky action row after the first
    // engine completes; force only this DOM click while retaining the real
    // browser assertion and result checks below.
    await page.getByRole('button', { name: 'Run all' }).click({ force: true });
    await expect(page.getByRole('heading', { name: 'Results' })).toBeVisible();
    await expect(page.getByText('Complete', { exact: true })).toBeVisible();
    await expect(page.getByRole('region', { name: 'Query result grid' })).toBeVisible();
  }

  for (const connection of connections) {
    const database = connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture';
    const schema = connection.engine === 'postgresql' ? 'public' : undefined;
    const table = realTables.get(connection.id)!;
    const quotedTable = connection.engine === 'postgresql' ? `"${table}"` : `\`${table}\``;
    const tabSessionId = `manual-transaction-${connection.engine}-${runLabel}`;
    const execute = async (sql: string, allowFailure = false) => {
      const response = await page.request.post('/api/v1/query/executions', {
        data: {
          connectionId: connection.id,
          database,
          schema,
          sql,
          mode: 'full',
          tabSessionId,
        },
        headers: { 'x-myadmin-csrf': '1' },
      });
      expect(response.status()).toBe(202);
      const executionId = ((await response.json()) as { executionId: string }).executionId;
      for (let attempt = 0; attempt < 100; attempt += 1) {
        const current = await page.request.get(`/api/v1/query/executions/${executionId}`);
        expect(current.ok()).toBe(true);
        const snapshot = (await current.json()) as {
          state: string;
          transactionActive?: boolean;
          error?: { position?: number };
          statements?: Array<{
            state: string;
            result?: { rows?: Array<Record<string, { type?: string; value?: unknown }>> };
          }>;
        };
        if (snapshot.state === 'completed') return snapshot;
        if (snapshot.state === 'failed') {
          if (allowFailure) return snapshot;
          throw new Error(
            `Real ${connection.engine} transaction query failed: ${JSON.stringify(snapshot.error ?? 'unknown error')}`,
          );
        }
        expect(['queued', 'running']).toContain(snapshot.state);
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
      throw new Error(`Real ${connection.engine} transaction query did not complete`);
    };

    const begun = await execute('BEGIN;');
    expect(begun.transactionActive).toBe(true);
    const inserted = await execute(
      `INSERT INTO ${quotedTable} (name) VALUES ('manual transaction rollback');`,
    );
    expect(inserted.transactionActive).toBe(true);
    const rolledBack = await execute('ROLLBACK;');
    expect(rolledBack.transactionActive).toBe(false);
    const verified = await execute(
      `SELECT COUNT(*) AS count FROM ${quotedTable} WHERE name = 'manual transaction rollback';`,
    );
    const count = verified.statements?.[0]?.result?.rows?.[0]?.['count'];
    expect(['number', 'string']).toContain(count?.type);
    expect(count?.value).toBe('0');

    const multiStatement = await execute('SELECT 1;\nSELEC;\nSELECT 2;', true);
    expect(multiStatement.state).toBe('failed');
    expect(multiStatement.statements?.map((statement) => statement.state)).toEqual([
      'done',
      'error',
      'skipped',
    ]);
    expect(multiStatement.error?.position).toEqual(expect.any(Number));
  }

  for (const connection of connections) {
    const database = connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture';
    const schema = connection.engine === 'postgresql' ? 'public' : undefined;
    const sleepSql =
      connection.engine === 'postgresql' ? 'SELECT pg_sleep(60);' : 'SELECT SLEEP(60);';
    const executionResponse = await page.request.post('/api/v1/query/executions', {
      data: {
        connectionId: connection.id,
        database,
        schema,
        sql: sleepSql,
        mode: 'full',
        tabSessionId: `cancel-${connection.engine}`,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(executionResponse.status()).toBe(202);
    const executionId = ((await executionResponse.json()) as { executionId: string }).executionId;
    let running = false;
    for (let attempt = 0; attempt < 100; attempt += 1) {
      const current = await page.request.get(`/api/v1/query/executions/${executionId}`);
      expect(current.ok()).toBe(true);
      const snapshot = (await current.json()) as { state: string };
      if (snapshot.state === 'running') {
        running = true;
        break;
      }
      expect(['queued', 'running']).toContain(snapshot.state);
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
    expect(running).toBe(true);
    const cancelResponse = await page.request.post(
      `/api/v1/query/executions/${executionId}/cancel`,
      { headers: { 'x-myadmin-csrf': '1' } },
    );
    expect(cancelResponse.status()).toBe(200);
    for (let attempt = 0; attempt < 100; attempt += 1) {
      const current = await page.request.get(`/api/v1/query/executions/${executionId}`);
      const snapshot = (await current.json()) as { state: string };
      if (snapshot.state === 'cancelled') break;
      expect(['queued', 'running', 'cancelling']).toContain(snapshot.state);
      await new Promise((resolve) => setTimeout(resolve, 50));
      if (attempt === 99) throw new Error(`Real ${connection.engine} query did not cancel`);
    }

    const explainResponse = await page.request.post('/api/v1/query/explain', {
      data: {
        connectionId: connection.id,
        database,
        schema,
        sql: 'SELECT 1;',
        tabSessionId: `cancel-${connection.engine}`,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(explainResponse.status()).toBe(200);
    expect((await explainResponse.json()) as { planText: string }).toMatchObject({
      planText: expect.any(String),
    });
  }

  for (const connection of connections) {
    const tableRef = {
      database: connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture',
      schema: connection.engine === 'postgresql' ? 'public' : null,
      name: realTables.get(connection.id)!,
      type: 'table' as const,
    };
    await page.goto(
      `/data-browser?connection=${encodeURIComponent(connection.id)}&ref=${encodeURIComponent(JSON.stringify(tableRef))}`,
    );
    await expect(
      page.getByRole('heading', {
        name: `${tableRef.schema ? `${tableRef.schema}.` : ''}${tableRef.name}`,
      }),
    ).toBeVisible();
    await expect(page.getByRole('grid')).toBeVisible();
    await expect(page.getByRole('gridcell', { name: 'name: browser fixture' })).toBeVisible();
    await expect(page.getByText('1 row', { exact: true })).toBeVisible();

    await page.getByRole('button', { name: 'Add row' }).click();
    await expect(page.getByRole('dialog', { name: 'Insert row' })).toBeVisible();
    await page
      .getByRole('dialog', { name: 'Insert row' })
      .getByRole('textbox')
      .last()
      .fill('browser inserted');
    const insertResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/data/rows') && response.request().method() === 'POST',
    );
    await page
      .getByRole('dialog', { name: 'Insert row' })
      .getByRole('button', { name: 'Insert row' })
      .click();
    await expect((await insertResponse).status()).toBe(200);
    await expect(page.getByRole('gridcell', { name: 'name: browser inserted' })).toBeVisible();

    await page.getByRole('gridcell', { name: 'name: browser fixture' }).dblclick();
    await expect(page.getByRole('dialog', { name: 'Edit name' })).toBeVisible();
    await page
      .getByRole('dialog', { name: 'Edit name' })
      .getByLabel('Cell value')
      .fill('browser updated');
    const updateResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/data/rows') && response.request().method() === 'PATCH',
    );
    await page
      .getByRole('dialog', { name: 'Edit name' })
      .getByRole('button', { name: 'Save cell' })
      .click();
    await expect((await updateResponse).status()).toBe(200);
    await expect(page.getByRole('gridcell', { name: 'name: browser updated' })).toBeVisible();

    await page
      .getByRole('gridcell', { name: 'name: browser inserted' })
      .locator('..')
      .getByRole('checkbox')
      .check();
    await page.getByRole('button', { name: 'Delete selected' }).click();
    await expect(page.getByRole('dialog', { name: 'Delete selected rows?' })).toBeVisible();
    const deleteResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/data/rows/delete') &&
        response.request().method() === 'POST',
    );
    await page
      .getByRole('dialog', { name: 'Delete selected rows?' })
      .getByRole('button', { name: 'Delete rows' })
      .click();
    await expect((await deleteResponse).status()).toBe(200);
    await expect(page.getByRole('gridcell', { name: 'name: browser inserted' })).toHaveCount(0);
  }

  for (const connection of connections) {
    const tableRef = {
      database: connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture',
      schema: connection.engine === 'postgresql' ? 'public' : null,
      name: realTables.get(connection.id)!,
      type: 'table' as const,
    };
    await page.goto(
      `/table-designer?connection=${encodeURIComponent(connection.id)}&ref=${encodeURIComponent(JSON.stringify(tableRef))}`,
    );
    await expect(page.getByRole('heading', { name: 'Design table' })).toBeVisible();
    await expect(page.locator('input.column-name')).toHaveCount(2);
    await page.getByRole('button', { name: 'Add column' }).click();
    await expect(page.locator('input.column-name')).toHaveCount(3);
    await page.locator('input.column-name').last().fill('browser_extra');
    const previewResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/preview') &&
        response.request().method() === 'POST',
    );
    const previewRequest = page.waitForRequest(
      (request) =>
        request.url().includes('/api/v1/tables/ddl/preview') && request.method() === 'POST',
    );
    await page.getByRole('button', { name: 'Preview SQL' }).click();
    const previewHttpResponse = await previewResponse;
    const previewPayload = await previewRequest;
    expect(previewHttpResponse.status(), JSON.stringify(previewPayload.postDataJSON())).toBe(200);
    await expect(page.getByText('browser_extra', { exact: false })).toBeVisible();
    const applyResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/apply') &&
        response.request().method() === 'POST',
    );
    const applyRequest = page.waitForRequest(
      (request) =>
        request.url().includes('/api/v1/tables/ddl/apply') && request.method() === 'POST',
    );
    await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
    const applyHttpResponse = await applyResponse;
    const applyHttpRequest = await applyRequest;
    expect(
      applyHttpResponse.status(),
      `${await applyHttpResponse.text()} headers=${JSON.stringify(applyHttpRequest.headers())}`,
    ).toBe(200);
    await expect(
      page.getByText('Table changes applied. Explorer metadata was refreshed.', { exact: true }),
    ).toBeVisible();
    await page.goto(
      `/table-designer?connection=${encodeURIComponent(connection.id)}&ref=${encodeURIComponent(JSON.stringify(tableRef))}`,
    );
    await expect(page.locator('input.column-name')).toHaveCount(3);
    await page.locator('input.column-name').nth(1).fill('browser_renamed');
    const renamePreviewResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/preview') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Preview SQL' }).click();
    expect((await renamePreviewResponse).status()).toBe(200);
    const renameApplyResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/apply') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
    expect((await renameApplyResponse).status()).toBe(200);
    await expect(
      page.getByText('Table changes applied. Explorer metadata was refreshed.', { exact: true }),
    ).toBeVisible();
    await page.goto(
      `/table-designer?connection=${encodeURIComponent(connection.id)}&ref=${encodeURIComponent(JSON.stringify(tableRef))}`,
    );
    await expect(page.locator('input.column-name')).toHaveCount(3);
    await page
      .locator('article.column-card')
      .nth(2)
      .getByRole('button', { name: 'Remove column' })
      .click();
    const dropPreviewResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/preview') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Preview SQL' }).click();
    expect((await dropPreviewResponse).status()).toBe(200);
    await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
    await expect(
      page.getByRole('dialog', { name: 'Apply destructive table changes?' }),
    ).toBeVisible();
    await expect(page.getByRole('dialog').getByText(/browser_extra/)).toBeVisible();
    const dropApplyResponse = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/apply') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Confirm destructive apply' }).click();
    expect((await dropApplyResponse).status()).toBe(200);
    await expect(
      page.getByText('Table changes applied. Explorer metadata was refreshed.', { exact: true }),
    ).toBeVisible();
    await page.goto(
      `/data-browser?connection=${encodeURIComponent(connection.id)}&ref=${encodeURIComponent(JSON.stringify(tableRef))}`,
    );
    await expect(page.getByRole('columnheader', { name: /browser_renamed/ })).toBeVisible();
    await expect(page.getByRole('columnheader', { name: /browser_extra/ })).toHaveCount(0);
  }

  // Exercise the table-operation service against both disposable engines
  // after the designer flow has finished using the fixture table.
  for (const connection of connections) {
    const database = connection.engine === 'postgresql' ? 'myadmin_test' : 'fixture';
    const schema = connection.engine === 'postgresql' ? 'public' : null;
    const currentName = realTables.get(connection.id)!;
    const currentRef = { database, schema, name: currentName, type: 'table' as const };
    const renamedName = `${currentName}_renamed`;
    const renameResponse = await page.request.post('/api/v1/tables/rename', {
      data: {
        connectionId: connection.id,
        ref: currentRef,
        newName: renamedName,
        confirmName: currentName,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(renameResponse.status()).toBe(200);
    const renamedRef = { ...currentRef, name: renamedName };
    const truncateResponse = await page.request.post('/api/v1/tables/truncate', {
      data: {
        connectionId: connection.id,
        ref: renamedRef,
        restartIdentity: false,
        confirmName: renamedName,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(truncateResponse.status()).toBe(204);
    const dropResponse = await page.request.delete('/api/v1/tables/drop', {
      data: { connectionId: connection.id, ref: renamedRef, confirmName: renamedName },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(dropResponse.status()).toBe(204);
    const audit = await page.request.get('/api/v1/audit?page=1&pageSize=100');
    expect(audit.ok()).toBe(true);
    const auditBody = JSON.stringify(await audit.json());
    expect(auditBody).toContain('table.renamed');
    expect(auditBody).toContain('table.truncated');
    expect(auditBody).toContain('table.dropped');
  }

  await page.goto('/explorer');
  await expect(page.getByRole('heading', { name: 'Object explorer' })).toBeVisible();
  const explorerViewport = page.locator('.explorer-viewport');
  for (const connection of connections) {
    await explorerViewport.evaluate((element) => element.scrollTo({ top: 0, behavior: 'instant' }));
    const connectionNode = page.getByRole('treeitem', { name: connection.label });
    await expect(connectionNode).toBeVisible();
    await connectionNode.click();
    const searchPrefix = searchPrefixes.get(connection.id)!;
    const searchStartedAt = performance.now();
    await page.getByLabel('Search objects').fill(searchPrefix);
    await expect(page.getByRole('option')).toHaveCount(50);
    expect(performance.now() - searchStartedAt).toBeLessThan(5_000);
    await page.getByRole('button', { name: 'Load more results' }).click();
    await expect(page.getByRole('option')).toHaveCount(100);
    const searchedOption = page.getByRole('option', {
      name: new RegExp(`${searchPrefix}_0000 in`),
    });
    await expect(searchedOption).toBeVisible();
    await searchedOption.click();
    const searchedTable = page.getByRole('treeitem', {
      name: new RegExp(`${searchPrefix}_0000`),
    });
    await expect(searchedTable).toBeVisible({ timeout: 30_000 });
    await searchedTable
      .getByRole('button', { name: new RegExp(`Expand ${searchPrefix}_0000`) })
      .click();
    await expect(page.getByRole('treeitem', { name: 'id', exact: true })).toBeVisible();
  }

  // This spec runs with Playwright's disposable server/data directory. The
  // server shutdown closes provider handles; keeping HTTP teardown out of the
  // assertion path avoids conflating browser query proof with lifecycle cleanup.
});

test('E2E-0044-AC1, E2E-0044-AC2, E2E-0044-AC5, E2E-0044-AC6, and E2E-0044-AC7 render a real PostgreSQL view preview and confirmation gate', async ({
  page,
}) => {
  test.setTimeout(120_000);
  const setupStatus = await page.request.get('/api/v1/setup/status');
  expect(setupStatus.ok()).toBe(true);
  if (!((await setupStatus.json()) as { initialized: boolean }).initialized) {
    const setup = await page.request.post('/api/v1/setup/admin', { data: admin });
    expect(setup.status()).toBe(201);
  }

  await page.goto('/login');
  await page.getByLabel('Username').fill(admin.username);
  await page.getByLabel('Password').fill(admin.password);
  await page.getByLabel('Password').press('Enter');
  await expect(page).toHaveURL(/\/workspace$/);

  const connectionResponse = await page.request.post('/api/v1/connections', {
    data: {
      label: `e2e_0044_${crypto.randomUUID().replaceAll('-', '').slice(0, 10)}`,
      engine: 'postgresql',
      host: '127.0.0.1',
      port: 55433,
      database: 'myadmin_test',
      username: 'myadmin_test',
      sslMode: 'disable',
      tlsOptions: null,
      connectTimeoutMs: 5_000,
      groupId: null,
      tag: 'e2e',
      color: null,
      secret: 'myadmin_test_password',
      saveSecret: true,
    },
    headers: { 'x-myadmin-csrf': '1' },
  });
  expect(connectionResponse.status()).toBe(201);
  const connectionId = ((await connectionResponse.json()) as { id: string }).id;
  const connected = await page.request.post(`/api/v1/connections/${connectionId}/connect`, {
    data: { secret: 'myadmin_test_password' },
    headers: { 'x-myadmin-csrf': '1' },
  });
  expect(connected.status()).toBe(200);

  const viewName = `e2e_view_${crypto.randomUUID().replaceAll('-', '').slice(0, 12)}`;
  const ref = { database: 'myadmin_test', schema: 'public', name: viewName, type: 'view' as const };
  const encodedRef = encodeURIComponent(JSON.stringify(ref));
  await page.goto(
    `/view-editor?connection=${encodeURIComponent(connectionId)}&database=myadmin_test&schema=public&mode=create`,
  );
  await expect(page.getByRole('heading', { name: 'Create view' })).toBeVisible();
  await page.getByLabel('View name').fill(viewName);
  await page.locator('.cm-content').fill('SELECT 1 AS value;');
  await page.getByRole('button', { name: 'Validate' }).click();
  await expect(page.locator('main[aria-labelledby="view-editor-title"]')).toContainText(
    'Definition is valid',
  );
  await page.getByRole('button', { name: 'Preview DDL' }).click();
  await expect(page.locator('pre')).toContainText('CREATE VIEW');
  const createResponse = page.waitForResponse(
    (response) =>
      response.url().endsWith('/api/v1/views') && response.request().method() === 'POST',
  );
  await page.getByRole('button', { name: 'Create view', exact: true }).click();
  expect((await createResponse).status()).toBe(201);
  await expect(page.locator('main[aria-labelledby="view-editor-title"]')).toContainText(
    'View created.',
  );

  await page.goto(
    `/view-editor?connection=${encodeURIComponent(connectionId)}&database=myadmin_test&schema=public&mode=drop&ref=${encodedRef}`,
  );
  await expect(page.getByRole('heading', { name: 'Drop view' })).toBeVisible();
  const dropPreviewResponse = page.waitForResponse(
    (response) =>
      response.url().endsWith('/api/v1/views/ddl/drop-preview') &&
      response.request().method() === 'POST',
  );
  await page.getByRole('button', { name: 'Drop view', exact: true }).click();
  expect((await dropPreviewResponse).status()).toBe(200);
  await expect(page.getByRole('alertdialog')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Confirm', exact: true })).toBeDisabled();
  await page.getByLabel('Exact view name').fill(viewName);
  await expect(page.getByRole('button', { name: 'Confirm', exact: true })).toBeEnabled();
  const deleteResponse = page.waitForResponse(
    (response) =>
      response.url().includes('/api/v1/views/') && response.request().method() === 'DELETE',
  );
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  expect((await deleteResponse).status()).toBe(204);
  await expect(page.locator('main[aria-labelledby="view-editor-title"]')).toContainText(
    'View dropped.',
  );
  const audit = await page.request.get('/api/v1/audit?page=1&pageSize=100');
  expect(audit.ok()).toBe(true);
  const auditBody = JSON.stringify(await audit.json());
  expect(auditBody).toContain('view.created');
  expect(auditBody).toContain('view.dropped');
});

test('E2E-0044-AC8 creates and drops a real MySQL view through the UI', async ({ page }) => {
  test.setTimeout(120_000);
  const setupStatus = await page.request.get('/api/v1/setup/status');
  expect(setupStatus.ok()).toBe(true);
  if (!((await setupStatus.json()) as { initialized: boolean }).initialized) {
    const setup = await page.request.post('/api/v1/setup/admin', { data: admin });
    expect(setup.status()).toBe(201);
  }

  await page.goto('/login');
  await page.getByLabel('Username').fill(admin.username);
  await page.getByLabel('Password').fill(admin.password);
  await page.getByLabel('Password').press('Enter');
  await expect(page).toHaveURL(/\/workspace$/);

  const connectionResponse = await page.request.post('/api/v1/connections', {
    data: {
      label: `e2e_0044_mysql_${crypto.randomUUID().replaceAll('-', '').slice(0, 10)}`,
      engine: 'mysql',
      host: '127.0.0.1',
      port: 3380,
      database: 'fixture',
      username: 'root',
      sslMode: 'require',
      tlsOptions: null,
      connectTimeoutMs: 5_000,
      groupId: null,
      tag: 'e2e',
      color: null,
      secret: 'myadmin-test-root',
      saveSecret: true,
    },
    headers: { 'x-myadmin-csrf': '1' },
  });
  expect(connectionResponse.status()).toBe(201);
  const connectionId = ((await connectionResponse.json()) as { id: string }).id;
  const connected = await page.request.post(`/api/v1/connections/${connectionId}/connect`, {
    data: { secret: 'myadmin-test-root' },
    headers: { 'x-myadmin-csrf': '1' },
  });
  expect(connected.status()).toBe(200);

  const viewName = `e2e_view_${crypto.randomUUID().replaceAll('-', '').slice(0, 12)}`;
  const ref = { database: 'fixture', schema: null, name: viewName, type: 'view' as const };
  const encodedRef = encodeURIComponent(JSON.stringify(ref));
  await page.goto(
    `/view-editor?connection=${encodeURIComponent(connectionId)}&database=fixture&mode=create`,
  );
  await expect(page.getByRole('heading', { name: 'Create view' })).toBeVisible();
  await page.getByLabel('View name').fill(viewName);
  await page.locator('.cm-content').fill('SELECT 1 AS value;');
  await page.getByRole('button', { name: 'Validate' }).click();
  await expect(page.locator('main[aria-labelledby="view-editor-title"]')).toContainText(
    'Definition is valid',
  );
  await page.getByRole('button', { name: 'Preview DDL' }).click();
  await expect(page.locator('pre')).toContainText('CREATE VIEW');
  const createResponse = page.waitForResponse(
    (response) =>
      response.url().endsWith('/api/v1/views') && response.request().method() === 'POST',
  );
  await page.getByRole('button', { name: 'Create view', exact: true }).click();
  expect((await createResponse).status()).toBe(201);
  await expect(page.locator('main[aria-labelledby="view-editor-title"]')).toContainText(
    'View created.',
  );

  await page.goto(
    `/view-editor?connection=${encodeURIComponent(connectionId)}&database=fixture&mode=drop&ref=${encodedRef}`,
  );
  await expect(page.getByRole('heading', { name: 'Drop view' })).toBeVisible();
  const dropPreviewResponse = page.waitForResponse(
    (response) =>
      response.url().endsWith('/api/v1/views/ddl/drop-preview') &&
      response.request().method() === 'POST',
  );
  await page.getByRole('button', { name: 'Drop view', exact: true }).click();
  expect((await dropPreviewResponse).status()).toBe(200);
  await expect(page.getByRole('alertdialog')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Confirm', exact: true })).toBeDisabled();
  await page.getByLabel('Exact view name').fill(viewName);
  await expect(page.getByRole('button', { name: 'Confirm', exact: true })).toBeEnabled();
  const deleteResponse = page.waitForResponse(
    (response) =>
      response.url().includes('/api/v1/views/') && response.request().method() === 'DELETE',
  );
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  expect((await deleteResponse).status()).toBe(204);
  await expect(page.locator('main[aria-labelledby="view-editor-title"]')).toContainText(
    'View dropped.',
  );
});

test('E2E-0042-AC3, E2E-0042-AC5, E2E-0042-AC6, and E2E-0042-AC8 create FK and composite unique, then drop an index on both engines', async ({
  page,
}) => {
  test.setTimeout(300_000);
  const setupStatus = await page.request.get('/api/v1/setup/status');
  expect(setupStatus.ok()).toBe(true);
  if (!((await setupStatus.json()) as { initialized: boolean }).initialized) {
    const setup = await page.request.post('/api/v1/setup/admin', { data: admin });
    expect(setup.status()).toBe(201);
  }

  await page.goto('/login');
  await page.getByLabel('Username').fill(admin.username);
  await page.getByLabel('Password').fill(admin.password);
  await page.getByLabel('Password').press('Enter');
  await expect(page).toHaveURL(/\/workspace$/);

  const engines: Array<{
    engine: 'postgresql' | 'mysql';
    label: string;
    port: number;
    database: string;
    schema: string | null;
    username: string;
    secret: string;
  }> = [
    {
      engine: 'postgresql',
      label: 'Real PostgreSQL 0042',
      port: 55433,
      database: 'myadmin_test',
      schema: 'public',
      username: 'myadmin_test',
      secret: 'myadmin_test_password',
    },
    {
      engine: 'mysql',
      label: 'Real MySQL 0042',
      port: 3380,
      database: 'fixture',
      schema: null,
      username: 'fixture',
      secret: 'myadmin-test-password',
    },
  ];

  for (const engine of engines) {
    const connectionResponse = await page.request.post('/api/v1/connections', {
      data: {
        label: engine.label,
        engine: engine.engine,
        host: '127.0.0.1',
        port: engine.port,
        database: engine.database,
        username: engine.username,
        sslMode: engine.engine === 'postgresql' ? 'disable' : 'require',
        tlsOptions: null,
        connectTimeoutMs: 5_000,
        groupId: null,
        tag: 'e2e',
        color: null,
        secret: engine.secret,
        saveSecret: true,
      },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(connectionResponse.status()).toBe(201);
    const connectionId = ((await connectionResponse.json()) as { id: string }).id;
    const connected = await page.request.post(`/api/v1/connections/${connectionId}/connect`, {
      data: { secret: engine.secret },
      headers: { 'x-myadmin-csrf': '1' },
    });
    expect(connected.status()).toBe(200);

    const suffix = crypto.randomUUID().replaceAll('-', '').slice(0, 10);
    const parent = `e2e_0042_parent_${suffix}`;
    const child = `e2e_0042_child_${suffix}`;
    const quote = engine.engine === 'postgresql' ? '"' : '`';
    const qualified = (name: string): string =>
      engine.schema
        ? `${quote}${engine.schema}${quote}.${quote}${name}${quote}`
        : `${quote}${name}${quote}`;
    const setupStatements = [
      `CREATE TABLE ${qualified(parent)} (id integer PRIMARY KEY, region integer NOT NULL, code integer NOT NULL);`,
      `CREATE TABLE ${qualified(child)} (id integer PRIMARY KEY, parent_id integer NOT NULL, region integer NOT NULL, code integer NOT NULL);`,
      `CREATE INDEX ${quote}idx_0042_drop_${suffix}${quote} ON ${qualified(child)} (${quote}code${quote});`,
    ];
    for (const [statementIndex, sql] of setupStatements.entries()) {
      const execution = await page.request.post('/api/v1/query/executions', {
        data: {
          connectionId,
          database: engine.database,
          schema: engine.schema ?? engine.database,
          sql,
          mode: 'full',
          tabSessionId: `setup-0042-${engine.engine}-${statementIndex}`,
        },
        headers: { 'x-myadmin-csrf': '1' },
      });
      expect(execution.status()).toBe(202);
      const executionId = ((await execution.json()) as { executionId: string }).executionId;
      for (let attempt = 0; attempt < 100; attempt += 1) {
        const current = await page.request.get(`/api/v1/query/executions/${executionId}`);
        expect(current.ok()).toBe(true);
        const state = (await current.json()) as { state: string; error?: string };
        if (state.state === 'completed') break;
        expect(['queued', 'running']).toContain(state.state);
        await new Promise((resolve) => setTimeout(resolve, 100));
        if (attempt === 99)
          throw new Error(
            `Real ${engine.engine} 0042 setup statement ${statementIndex} did not complete`,
          );
      }
    }

    const childRef = {
      database: engine.database,
      schema: engine.schema,
      name: child,
      type: 'table' as const,
    };
    await page.goto(
      `/table-designer?connection=${encodeURIComponent(connectionId)}&ref=${encodeURIComponent(JSON.stringify(childRef))}`,
    );
    await expect(page.getByRole('heading', { name: 'Design table' })).toBeVisible();

    await page.getByRole('button', { name: /Constraints/ }).click();
    await page.getByRole('button', { name: 'Add FK' }).click();
    await expect(page.locator('.structure-card')).toHaveCount(2);
    const constraint = page.locator('.structure-card').nth(1);
    await constraint.locator('input').nth(0).fill(`fk_${suffix}`);
    await constraint.getByLabel('Columns, comma separated').fill('parent_id');
    await constraint.getByLabel('Target table').fill(parent);
    await expect(page.getByRole('button', { name: new RegExp(parent) })).toBeVisible();
    await page.getByRole('button', { name: new RegExp(parent) }).click();
    await constraint.getByLabel('Target columns').fill('id');
    await constraint.getByLabel('On delete').selectOption('CASCADE');
    // Keep the provider default for ON UPDATE; the selected ON DELETE rule is
    // asserted below and the preview still exercises the complete FK path.
    const fkPreview = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/preview') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Preview SQL' }).click();
    const fkPreviewResponse = await fkPreview;
    expect(fkPreviewResponse.status()).toBe(200);
    await expect(
      page.locator('.statement-card pre').filter({ hasText: new RegExp(`fk_${suffix}`) }),
    ).toBeVisible();
    await expect(
      page.locator('.statement-card pre').filter({ hasText: /FOREIGN KEY/i }),
    ).toBeVisible();
    await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
    await expect(page.locator('main.table-designer-page').getByRole('status')).toContainText(
      'Explorer metadata was refreshed',
    );

    await page.getByRole('button', { name: /Constraints/ }).click();
    await page.getByRole('button', { name: 'Add unique' }).click();
    await expect(page.locator('.structure-card')).toHaveCount(3);
    const uniqueConstraint = page.locator('.structure-card').nth(2);
    await uniqueConstraint.locator('input').nth(0).fill(`uq_${suffix}`);
    await uniqueConstraint.getByLabel('Columns, comma separated').fill('region, code');
    const uniquePreview = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/preview') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Preview SQL' }).click();
    const uniquePreviewResponse = await uniquePreview;
    expect(uniquePreviewResponse.status()).toBe(200);
    await expect(
      page.locator('.statement-card pre').filter({ hasText: new RegExp(`uq_${suffix}`) }),
    ).toBeVisible();
    await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
    await expect(page.locator('main.table-designer-page').getByRole('status')).toContainText(
      'Explorer metadata was refreshed',
    );

    await page.getByRole('button', { name: /Indexes/ }).click();
    const dropIndex = page
      .locator('.structure-card')
      .filter({ hasText: `idx_0042_drop_${suffix}` });
    await expect(dropIndex).toHaveCount(1);
    await dropIndex.getByRole('button', { name: 'Remove index' }).click();
    const dropPreview = page.waitForResponse(
      (response) =>
        response.url().includes('/api/v1/tables/ddl/preview') &&
        response.request().method() === 'POST',
    );
    await page.getByRole('button', { name: 'Preview SQL' }).click();
    const dropPreviewResponse = await dropPreview;
    expect(dropPreviewResponse.status()).toBe(200);
    await expect(page.getByRole('button', { name: 'Apply reviewed changes' })).toBeVisible();
    await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
    await expect(
      page.getByRole('dialog', { name: 'Apply destructive table changes?' }),
    ).toBeVisible();
    await page
      .getByRole('dialog', { name: 'Apply destructive table changes?' })
      .getByRole('button', {
        name: 'Confirm destructive apply',
      })
      .click();
    await expect(page.locator('main.table-designer-page').getByRole('status')).toContainText(
      'Explorer metadata was refreshed',
    );
  }
});
