import { expect, test, type Page } from '../fixtures';

const catalog = {
  engine: 'postgresql',
  version: '16.4',
  types: [
    { name: 'integer', label: 'Integer', parameters: [] },
    { name: 'varchar', label: 'Variable character', parameters: ['length'] },
    { name: 'numeric', label: 'Numeric', parameters: ['precision', 'scale'] },
  ],
  capability: {
    engine: 'postgresql',
    version: '16.4',
    capabilities: {
      generatedColumns: true,
      identityColumns: true,
      tableComments: true,
    },
  },
  rules: {
    onDelete: ['NO ACTION', 'RESTRICT', 'CASCADE', 'SET NULL', 'SET DEFAULT'],
    onUpdate: ['NO ACTION', 'RESTRICT', 'CASCADE', 'SET NULL', 'SET DEFAULT'],
    maxColumns: 32,
  },
};

async function mockTableDesignerShell(page: Page): Promise<void> {
  await page.route('**/api/v1/setup/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ initialized: true }),
    });
  });
  await page.route('**/api/v1/auth/me', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ id: 'designer-admin', username: 'designer-admin', role: 'admin' }),
    });
  });
  await page.route('**/api/v1/connections/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        items: [
          {
            id: 'pg-1',
            label: 'PostgreSQL fixture',
            engine: 'postgresql',
            connectionId: 'pg-1',
            status: 'connected',
            changedAt: '2026-08-29T00:00:00.000Z',
            serverInfo: { engine: 'postgresql', version: '16.4' },
            capability: catalog.capability,
            latencyMs: 2,
            errorCategory: null,
            reason: null,
          },
        ],
      }),
    });
  });
  await page.route('**/api/v1/workspace', async (route) => {
    const requestedUrl = new URL(page.url());
    const requestedRoute = `${requestedUrl.pathname}${requestedUrl.search}`;
    const requestedRef = requestedUrl.searchParams.get('ref');
    const tabId = `table-designer-${requestedRef ? requestedRef : 'create'}`
      .replace(/[^a-zA-Z0-9_-]/g, '-')
      .slice(0, 128);
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        version: 1,
        tabs: [
          {
            id: tabId,
            type: 'table-designer',
            title: 'Table designer',
            context: { route: requestedRoute, connectionId: 'pg-1' },
          },
        ],
        activeTabId: tabId,
        panels: { sidebarWidth: 22, bottomHeight: 24, sidebarCollapsed: false },
      }),
    });
  });
  await page.route('**/api/v1/preferences', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        'ui.theme': 'system',
        'ui.pageSize': 50,
        'editor.fontSize': 14,
        'editor.wordWrap': true,
      }),
    });
  });
  await page.route('**/api/v1/connections?page=*&pageSize=*', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ items: [], page: 1, pageSize: 20, total: 0 }),
    });
  });
  await page.route('**/api/v1/server-groups?page=*&pageSize=*', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ items: [], page: 1, pageSize: 100, total: 0 }),
    });
  });
  await page.route('**/api/v1/tables/ddl/types', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(catalog),
    });
  });
}

test('E2E-0041-AC1 and E2E-0041-AC3 create columns and unlock apply only after preview', async ({
  page,
}) => {
  let previewBody: unknown;
  let applyBody: unknown;
  await mockTableDesignerShell(page);
  await page.route('**/api/v1/tables/ddl/preview', async (route) => {
    previewBody = route.request().postDataJSON();
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        operation: 'create',
        statements: [
          {
            sql: 'CREATE TABLE "public"."accounts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY)',
          },
        ],
        warnings: ['Review the generated DDL before applying it.'],
        destructive: false,
      }),
    });
  });
  await page.route('**/api/v1/tables/ddl/apply', async (route) => {
    applyBody = route.request().postDataJSON();
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        operation: 'create',
        transactional: true,
        committed: true,
        statements: [
          {
            index: 0,
            sql: 'CREATE TABLE "public"."accounts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY)',
            status: 'success',
          },
        ],
      }),
    });
  });

  await page.goto('/table-designer?connection=pg-1&database=app&schema=public&mode=create');
  await expect(page.getByRole('heading', { name: 'Create a table' })).toBeVisible();
  await page.getByLabel('Table name').fill('accounts');
  await page.getByRole('textbox', { name: 'Column name' }).first().fill('id');
  await page.getByRole('combobox', { name: 'Type' }).first().selectOption('integer');
  await page.getByRole('checkbox', { name: 'Nullable' }).first().uncheck();
  await page.getByRole('checkbox', { name: 'Identity / auto increment' }).check();
  await page.getByRole('checkbox', { name: 'Primary key' }).check();
  await page.getByRole('button', { name: 'Preview SQL' }).click();

  await expect(page.getByText('CREATE TABLE "public"."accounts"')).toBeVisible();
  await expect(page.getByText('Review the generated DDL before applying it.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Apply reviewed changes' })).toBeEnabled();
  expect(
    (previewBody as { changeSet: { ref: unknown; columns: unknown[] } }).changeSet,
  ).toMatchObject({
    ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
    columns: [
      { name: 'id', dataType: 'integer', nullable: false, identity: true, primaryKey: true },
    ],
  });

  await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
  await expect(
    page.getByRole('status').filter({ hasText: 'Explorer metadata was refreshed' }),
  ).toBeVisible();
  expect((applyBody as { changeSet: { columns: unknown[] } }).changeSet.columns).toEqual(
    (previewBody as { changeSet: { columns: unknown[] } }).changeSet.columns,
  );
});

test('E2E-0041-AC2 and E2E-0041-AC7 loads described columns and refreshes after alter', async ({
  page,
}) => {
  let refreshed = false;
  await mockTableDesignerShell(page);
  await page.route('**/api/v1/connections/pg-1/objects/describe*', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
        columns: [
          { name: 'id', dataType: 'integer', nullable: false },
          { name: 'email', dataType: 'varchar(120)', nullable: true, comment: 'Email' },
        ],
        indexes: [],
        constraints: [],
      }),
    });
  });
  await page.route('**/api/v1/tables/ddl/preview', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        operation: 'alter',
        statements: [{ sql: 'ALTER TABLE "public"."accounts" ALTER COLUMN "email" SET NOT NULL' }],
        warnings: ['Changing a PostgreSQL type may rewrite or lock the table.'],
        destructive: false,
      }),
    });
  });
  await page.route('**/api/v1/tables/ddl/apply', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        operation: 'alter',
        transactional: true,
        committed: true,
        statements: [
          {
            index: 0,
            sql: 'ALTER TABLE "public"."accounts" ALTER COLUMN "email" SET NOT NULL',
            status: 'success',
          },
        ],
      }),
    });
  });
  await page.route('**/api/v1/connections?page=*&pageSize=*', async (route) => {
    refreshed = true;
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ items: [], page: 1, pageSize: 20, total: 0 }),
    });
  });

  const ref = encodeURIComponent(
    JSON.stringify({ database: 'app', schema: 'public', name: 'accounts', type: 'table' }),
  );
  await page.goto(`/table-designer?connection=pg-1&ref=${ref}`);
  await expect(page.getByRole('heading', { name: 'Design table' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Column name' })).toHaveCount(2);
  await page.getByRole('checkbox', { name: 'Nullable' }).nth(1).uncheck();
  await page.getByRole('button', { name: 'Preview SQL' }).click();
  await expect(page.getByText('ALTER TABLE "public"."accounts"')).toBeVisible();
  await page.getByRole('button', { name: 'Apply reviewed changes' }).click();
  await expect(
    page.getByRole('status').filter({ hasText: 'Explorer metadata was refreshed' }),
  ).toBeVisible();
  expect(refreshed).toBe(true);
});
