import { readFile } from 'node:fs/promises';
import { describe, expect, test } from 'bun:test';
import { generateContractTypes } from '../../scripts/codegen/generate-contract-types';
import { createApp } from '../../apps/server/src/app';
import {
  assertResponseMatchesContract,
  assertRouteCoverage,
  contractOperations,
  loadContract,
  responsePayload,
  serverOperations,
  type ContractOperation,
} from './harness';

const contractPath = new URL('../../dist/openapi-v1.yaml', import.meta.url).pathname;

function operation(operations: ContractOperation[], operationId: string): ContractOperation {
  const found = operations.find((candidate) => candidate.operationId === operationId);
  if (!found) {
    throw new Error(`Contract operation ${operationId} is missing`);
  }
  return found;
}

describe('API contract', () => {
  test('CT-0004-AC1 generates deterministic types from the bundled contract', async () => {
    generateContractTypes();
    const first = await readFile(
      new URL('../../packages/api-contract/src/generated/openapi.ts', import.meta.url),
      'utf8',
    );
    generateContractTypes();
    const second = await readFile(
      new URL('../../packages/api-contract/src/generated/openapi.ts', import.meta.url),
      'utf8',
    );

    expect(second).toBe(first);
    expect(second).toContain('This file was auto-generated by openapi-typescript.');
  });

  test('CT-0004-AC3 covers contract operations and server routes in both directions', async () => {
    const document = await loadContract(contractPath);
    assertRouteCoverage(contractOperations(document), serverOperations(createApp()));

    expect(() =>
      assertRouteCoverage(
        [operation(contractOperations(document), 'getHealth')],
        [
          { method: 'get', path: '/health' },
          { method: 'post', path: '/shadow-route' },
        ],
      ),
    ).toThrow(/Missing contract operations: POST \/shadow-route/);
  });

  test('CT-0004-AC4 validates the six initial response shapes with AJV', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const app = createApp();
    const request = async (input: string, init?: RequestInit): Promise<Response> =>
      app.handle(new Request(`http://localhost${input}`, init));
    const responses: Array<[string, Response]> = [];

    responses.push(['getHealth', await request('/health')]);
    responses.push(['getSetupStatus', await request('/setup/status')]);
    responses.push([
      'createInitialAdmin',
      await request('/setup/admin', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ username: 'contract-admin', password: 'synthetic-password' }),
      }),
    ]);
    responses.push([
      'login',
      await request('/auth/login', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ username: 'contract-admin', password: 'synthetic-password' }),
      }),
    ]);
    const loginCookie = responses[3]?.[1].headers.get('set-cookie');
    if (!loginCookie) {
      throw new Error('Login did not set a session cookie for contract validation');
    }
    const sessionCookieValue = loginCookie.split(';')[0] ?? '';
    responses.push([
      'getCurrentUser',
      await request('/auth/me', { headers: { cookie: sessionCookieValue } }),
    ]);
    responses.push([
      'logout',
      await request('/auth/logout', {
        method: 'POST',
        headers: { cookie: sessionCookieValue },
      }),
    ]);

    for (const [operationId, response] of responses) {
      assertResponseMatchesContract(
        document,
        operation(operations, operationId),
        response.status,
        await responsePayload(response),
      );
    }

    expect(() =>
      assertResponseMatchesContract(document, operation(operations, 'getHealth'), 200, {
        status: 'wrong',
        version: 1,
      }),
    ).toThrow(/\/status/);
  });

  test('CT-0004-AC5 returns ApiError for invalid requests', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const app = createApp();
    const invalidRequests: Array<[string, Request]> = [
      [
        'createInitialAdmin',
        new Request('http://localhost/setup/admin', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ username: '' }),
        }),
      ],
      [
        'login',
        new Request('http://localhost/auth/login', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ password: 'missing-username' }),
        }),
      ],
      ['logout', new Request('http://localhost/auth/logout', { method: 'POST' })],
      ['getCurrentUser', new Request('http://localhost/auth/me')],
    ];

    for (const [operationId, request] of invalidRequests) {
      const response = await app.handle(request);
      expect([401, 422]).toContain(response.status);
      assertResponseMatchesContract(
        document,
        operation(operations, operationId),
        response.status,
        await responsePayload(response),
      );
    }
  });
});
