import { readFile } from 'node:fs/promises';
import { describe, expect, test } from 'bun:test';
import { generateContractTypes } from '../../scripts/codegen/generate-contract-types';
import { createApp } from '../../apps/server/src/app';
import {
  assertResponseMatchesContract,
  assertRouteCoverage,
  contractOperations,
  loadContract,
  responsePayload,
  serverOperations,
  type ContractOperation,
} from './harness';

const contractPath = new URL('../../dist/openapi-v1.yaml', import.meta.url).pathname;

function operation(operations: ContractOperation[], operationId: string): ContractOperation {
  const found = operations.find((candidate) => candidate.operationId === operationId);
  if (!found) {
    throw new Error(`Contract operation ${operationId} is missing`);
  }
  return found;
}

describe('API contract', () => {
  test('CT-0004-AC1 generates deterministic types from the bundled contract', async () => {
    generateContractTypes();
    const first = await readFile(
      new URL('../../packages/api-contract/src/generated/openapi.ts', import.meta.url),
      'utf8',
    );
    generateContractTypes();
    const second = await readFile(
      new URL('../../packages/api-contract/src/generated/openapi.ts', import.meta.url),
      'utf8',
    );

    expect(second).toBe(first);
    expect(second).toContain('This file was auto-generated by openapi-typescript.');
  });

  test('CT-0004-AC3 covers contract operations and server routes in both directions', async () => {
    const document = await loadContract(contractPath);
    assertRouteCoverage(contractOperations(document), serverOperations(createApp()));

    expect(() =>
      assertRouteCoverage(
        [operation(contractOperations(document), 'getHealth')],
        [
          { method: 'get', path: '/health' },
          { method: 'post', path: '/shadow-route' },
        ],
      ),
    ).toThrow(/Missing contract operations: POST \/shadow-route/);
  });

  test('CT-0004-AC4 and CT-0030-AC1/CT-0030-AC2 validate response shapes with AJV', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const app = createApp();
    const request = async (input: string, init?: RequestInit): Promise<Response> =>
      app.handle(new Request(`http://localhost${input}`, init));
    const responses: Array<[string, Response]> = [];

    responses.push(['getHealth', await request('/health')]);
    responses.push(['getSetupStatus', await request('/setup/status')]);
    responses.push([
      'createInitialAdmin',
      await request('/setup/admin', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ username: 'contract-admin', password: 'synthetic-password' }),
      }),
    ]);
    responses.push([
      'login',
      await request('/auth/login', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ username: 'contract-admin', password: 'synthetic-password' }),
      }),
    ]);
    const loginCookie = responses[3]?.[1].headers.get('set-cookie');
    if (!loginCookie) {
      throw new Error('Login did not set a session cookie for contract validation');
    }
    const sessionCookieValue = loginCookie.split(';')[0] ?? '';
    responses.push([
      'getCurrentUser',
      await request('/auth/me', { headers: { cookie: sessionCookieValue } }),
    ]);
    responses.push([
      'getWorkspace',
      await request('/workspace', { headers: { cookie: sessionCookieValue } }),
    ]);
    responses.push([
      'saveWorkspace',
      await request('/workspace', {
        method: 'PUT',
        headers: {
          cookie: sessionCookieValue,
          'content-type': 'application/json',
          'X-Myadmin-Csrf': '1',
        },
        body: JSON.stringify({
          version: 1,
          tabs: [
            {
              id: 'workspace',
              type: 'workspace',
              title: 'Workspace',
              context: { route: '/workspace' },
            },
          ],
          activeTabId: 'workspace',
          panels: { sidebarWidth: 22, bottomHeight: 22, sidebarCollapsed: false },
        }),
      }),
    ]);
    responses.push([
      'logout',
      await request('/auth/logout', {
        method: 'POST',
        headers: { cookie: sessionCookieValue, 'X-Myadmin-Csrf': '1' },
      }),
    ]);

    for (const [operationId, response] of responses) {
      assertResponseMatchesContract(
        document,
        operation(operations, operationId),
        response.status,
        await responsePayload(response),
      );
    }

    expect(() =>
      assertResponseMatchesContract(document, operation(operations, 'getHealth'), 200, {
        status: 'wrong',
        version: 1,
      }),
    ).toThrow(/\/status/);
  });

  test('CT-0004-AC4 rejects malformed date-time values', () => {
    const document = {};
    const operation: ContractOperation = {
      method: 'get',
      path: '/example',
      operationId: 'example',
      responses: {
        '200': {
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: { createdAt: { type: 'string', format: 'date-time' } },
                required: ['createdAt'],
                additionalProperties: false,
              },
            },
          },
        },
      },
    };

    expect(() =>
      assertResponseMatchesContract(document, operation, 200, {
        createdAt: '2026-08-29T12:34:56.000Z',
      }),
    ).not.toThrow();
    expect(() =>
      assertResponseMatchesContract(document, operation, 200, {
        createdAt: 'not-a-date',
      }),
    ).toThrow(/\/createdAt.*date-time/);
  });

  test('CT-0004-AC5 returns ApiError for invalid requests', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const app = createApp();
    const invalidRequests: Array<[string, Request]> = [
      [
        'createInitialAdmin',
        new Request('http://localhost/setup/admin', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ username: '' }),
        }),
      ],
      [
        'login',
        new Request('http://localhost/auth/login', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ password: 'missing-username' }),
        }),
      ],
      ['logout', new Request('http://localhost/auth/logout', { method: 'POST' })],
      ['getCurrentUser', new Request('http://localhost/auth/me')],
    ];

    for (const [operationId, request] of invalidRequests) {
      const response = await app.handle(request);
      expect([401, 409, 422]).toContain(response.status);
      assertResponseMatchesContract(
        document,
        operation(operations, operationId),
        response.status,
        await responsePayload(response),
      );
    }
  });

  test('CT-0020-AC1 and CT-0020-AC5 validate the administrator audit operations', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const app = createApp();
    const request = async (input: string, init?: RequestInit): Promise<Response> =>
      app.handle(new Request(`http://localhost${input}`, init));

    const setup = await request('/setup/admin', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ username: 'audit-contract-admin', password: 'synthetic-password' }),
    });
    expect(setup.status).toBe(201);
    const login = await request('/auth/login', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ username: 'audit-contract-admin', password: 'synthetic-password' }),
    });
    const cookie = login.headers.get('set-cookie')?.split(';')[0];
    if (!cookie) throw new Error('Contract audit login did not set a session cookie');

    const list = await request('/audit?page=1&pageSize=10&action=auth.login_succeeded', {
      headers: { cookie },
    });
    const actions = await request('/audit/actions', { headers: { cookie } });
    const unauthenticated = await request('/audit');

    expect(list.status).toBe(200);
    expect(actions.status).toBe(200);
    expect(unauthenticated.status).toBe(401);
    assertResponseMatchesContract(
      document,
      operation(operations, 'queryAudit'),
      list.status,
      await responsePayload(list),
    );
    assertResponseMatchesContract(
      document,
      operation(operations, 'getAuditActions'),
      actions.status,
      await responsePayload(actions),
    );
    assertResponseMatchesContract(
      document,
      operation(operations, 'queryAudit'),
      unauthenticated.status,
      await responsePayload(unauthenticated),
    );
  });

  test('CT-0018-AC2 validates administrator user-management responses', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const app = createApp();
    const request = async (input: string, init?: RequestInit): Promise<Response> =>
      app.handle(new Request(`http://localhost${input}`, init));
    const json = (body: unknown, headers?: HeadersInit): RequestInit => ({
      method: 'POST',
      headers: { 'content-type': 'application/json', ...headers },
      body: JSON.stringify(body),
    });

    await request(
      '/setup/admin',
      json({ username: 'contract-admin', password: 'contract-admin-password' }),
    );
    const loginResponse = await request(
      '/auth/login',
      json({ username: 'contract-admin', password: 'contract-admin-password' }),
    );
    const cookie = loginResponse.headers.get('set-cookie')?.split(';', 1)[0];
    if (!cookie) throw new Error('Contract user-management test did not receive a session cookie');
    const mutationHeaders = { cookie, 'X-Myadmin-Csrf': '1' };

    const created = await request(
      '/users',
      json(
        { username: 'contract-user', password: 'contract-user-password', role: 'user' },
        mutationHeaders,
      ),
    );
    const createdPayload = await responsePayload(created);
    assertResponseMatchesContract(
      document,
      operation(operations, 'createUser'),
      created.status,
      createdPayload,
    );
    const userId = (createdPayload as { user: { id: string } }).user.id;

    const listed = await request('/users?page=1&pageSize=10', { headers: { cookie } });
    assertResponseMatchesContract(
      document,
      operation(operations, 'listUsers'),
      listed.status,
      await responsePayload(listed),
    );

    const updated = await request(`/users/${userId}`, {
      ...json({ isActive: false }, mutationHeaders),
      method: 'PATCH',
    });
    assertResponseMatchesContract(
      document,
      operation(operations, 'updateUser'),
      updated.status,
      await responsePayload(updated),
    );

    const reset = await request(
      `/users/${userId}/reset-password`,
      json({ newPassword: 'contract-reset-password' }, mutationHeaders),
    );
    assertResponseMatchesContract(
      document,
      operation(operations, 'resetUserPassword'),
      reset.status,
      await responsePayload(reset),
    );
  });

  test('CT-0026 validates connection manager response schemas', async () => {
    const document = await loadContract(contractPath);
    const operations = contractOperations(document);
    const connection = {
      id: 'connection-1',
      owner: { id: 'user-1', username: 'admin' },
      groupId: null,
      label: 'Production database',
      engine: 'postgresql',
      host: 'db.internal.test',
      port: 5432,
      database: 'app',
      username: 'app_user',
      sslMode: 'disable',
      tlsOptions: null,
      connectTimeoutMs: 3_000,
      tag: 'production',
      color: null,
      hasSavedSecret: true,
    };

    assertResponseMatchesContract(
      document,
      operation(operations, 'createConnection'),
      201,
      connection,
    );
    assertResponseMatchesContract(document, operation(operations, 'listConnections'), 200, {
      items: [connection],
      page: 1,
      pageSize: 20,
      total: 1,
    });
    assertResponseMatchesContract(document, operation(operations, 'testConnection'), 200, {
      success: true,
      version: 'fixture-16',
      latencyMs: 2,
    });
    assertResponseMatchesContract(document, operation(operations, 'createServerGroup'), 201, {
      id: 'group-1',
      name: 'Production',
      color: '#22c55e',
      sortOrder: 1,
    });
    assertResponseMatchesContract(document, operation(operations, 'listServerGroups'), 200, {
      items: [{ id: 'group-1', name: 'Production', color: '#22c55e', sortOrder: 1 }],
      page: 1,
      pageSize: 100,
      total: 1,
    });
  });
});
