import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import {
  ConnectionContext,
  type ConnectionHandle,
  type ObjectRef,
} from '../../../packages/database-core/src';
import { createPostgresqlProvider } from '../../../packages/database-postgresql/src';

const enabled = process.env['MYADMIN_POSTGRES_INTEGRATION'] === '1';
const port = Number(process.env['MYADMIN_POSTGRES_CURRENT_PORT'] ?? 55433);
const database = process.env['MYADMIN_POSTGRES_DATABASE'] ?? 'myadmin_test';
const schema = 'myadmin_metadata_0023';

function context() {
  return new ConnectionContext(
    {
      engine: 'postgresql',
      host: process.env['MYADMIN_POSTGRES_HOST'] ?? '127.0.0.1',
      port,
      user: process.env['MYADMIN_POSTGRES_USER'] ?? 'myadmin_test',
      database,
      tls: { mode: 'disable' },
      timeoutMs: 5000,
    },
    process.env['MYADMIN_POSTGRES_PASSWORD'] ?? 'myadmin_test_password',
  );
}

const schemaRef: ObjectRef = { database, schema, name: schema, type: 'schema' };
const ordersRef: ObjectRef = { database, schema, name: 'orders', type: 'table' };

describe('PostgreSQL metadata integration', () => {
  if (!enabled) {
    test.skip('requires MYADMIN_POSTGRES_INTEGRATION=1 and the pinned PostgreSQL service', () =>
      undefined);
    return;
  }

  const provider = createPostgresqlProvider();
  let handle: ConnectionHandle | undefined;

  beforeAll(async () => {
    handle = await provider.connection.open(context());
    const statements = [
      `DROP SCHEMA IF EXISTS "${schema}" CASCADE`,
      `CREATE SCHEMA "${schema}"`,
      `
        CREATE TABLE "${schema}"."customers" (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL
        )
      `,
      `
        CREATE TABLE "${schema}"."orders" (
          id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          customer_id bigint NOT NULL,
          email text NOT NULL,
          display_name text GENERATED ALWAYS AS (lower(email)) STORED,
          amount numeric DEFAULT 0,
          CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
            REFERENCES "${schema}"."customers" (id)
            ON UPDATE CASCADE ON DELETE RESTRICT,
          CONSTRAINT orders_email_unique UNIQUE (email),
          CONSTRAINT orders_amount_check CHECK (amount >= 0)
        )
      `,
      `
        CREATE UNIQUE INDEX orders_customer_email_idx
          ON "${schema}"."orders" USING btree (customer_id, email)
      `,
      `
        CREATE VIEW "${schema}"."order_view" AS
          SELECT id, email FROM "${schema}"."orders"
      `,
      `CREATE SEQUENCE "${schema}"."standalone_sequence"`,
      `
        CREATE FUNCTION "${schema}"."find_order"(order_id bigint)
          RETURNS text LANGUAGE SQL AS $$ SELECT email FROM "${schema}"."orders" WHERE id = order_id $$
      `,
      `
        CREATE PROCEDURE "${schema}"."refresh_orders"()
          LANGUAGE SQL AS $$ SELECT 1 $$
      `,
      `INSERT INTO "${schema}"."customers" (name) VALUES ('Customer')`,
      `
        INSERT INTO "${schema}"."orders" (customer_id, email, amount)
          VALUES (1, 'customer@example.test', 10)
      `,
      `COMMENT ON TABLE "${schema}"."orders" IS 'Orders'`,
      `COMMENT ON COLUMN "${schema}"."orders"."id" IS 'Order identifier'`,
      `ANALYZE "${schema}"."orders"`,
    ];
    for (const statement of statements) await provider.connection.execute(handle, statement);
  });

  afterAll(async () => {
    if (!handle) return;
    await provider.connection.execute(handle, `DROP SCHEMA IF EXISTS "${schema}" CASCADE;`);
    await provider.connection.close(handle);
  });

  test('[IT-0023-AC1] lists database metadata and defers database size', async () => {
    const databases = await provider.metadata.listDatabases(handle!, { limit: 500 });
    const current = databases.items.find((item) => item.name === database);

    expect(current).toMatchObject({
      name: database,
      encoding: expect.any(String),
      collation: expect.any(String),
    });
    expect(current?.sizeBytes).toBeUndefined();
    await expect(provider.metadata.getDatabaseSize(handle!, database)).resolves.toBeGreaterThan(0);
  });

  test('[IT-0023-AC2] lazily lists schemas and only requested object types', async () => {
    const schemas = await provider.metadata.listSchemas(handle!, database, { limit: 500 });
    expect(schemas.items.some((item) => item.name === schema && item.isSystem === false)).toBe(
      true,
    );
    expect(schemas.items.some((item) => item.name === 'pg_catalog')).toBe(false);

    const allSchemas = await provider.metadata.listSchemas(handle!, database, {
      includeSystem: true,
      limit: 500,
    });
    expect(allSchemas.items.some((item) => item.name === 'pg_catalog' && item.isSystem)).toBe(true);

    const page = await provider.metadata.listObjects(handle!, schemaRef, ['table'], { limit: 1 });
    expect(page.items).toHaveLength(1);
    expect(page.items[0]?.type).toBe('table');
    expect(page.cursor).toBeDefined();
  });

  test('[IT-0023-AC3] describes columns, constraints, indexes, comments, and estimates', async () => {
    const description = await provider.metadata.describeTable(handle!, ordersRef);
    const identity = description.columns.find((column) => column.name === 'id');
    const generated = description.columns.find((column) => column.name === 'display_name');
    const foreignKey = description.constraints.find(
      (constraint) => constraint.type === 'foreignKey',
    );
    const compositeIndex = description.indexes.find(
      (index) => index.name === 'orders_customer_email_idx',
    );

    expect(description).toMatchObject({ ref: ordersRef, comment: 'Orders' });
    expect(description.estimatedRows).toBeGreaterThanOrEqual(1);
    expect(identity).toMatchObject({ name: 'id', nullable: false, isIdentity: true });
    expect(identity?.comment).toBe('Order identifier');
    expect(generated).toMatchObject({
      name: 'display_name',
      isGenerated: true,
      generatedExpression: 'lower(email)',
    });
    expect(foreignKey).toMatchObject({
      name: 'orders_customer_fk',
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      referencedTable: { database, schema, name: 'customers', type: 'table' },
      referencedColumns: ['id'],
    });
    expect(description.constraints.map((constraint) => constraint.type)).toEqual(
      expect.arrayContaining(['primaryKey', 'foreignKey', 'unique', 'check']),
    );
    expect(compositeIndex).toMatchObject({
      columns: ['customer_id', 'email'],
      unique: true,
      method: 'btree',
    });
    await expect(provider.metadata.getTableSize(handle!, ordersRef)).resolves.toBeGreaterThan(0);
  });

  test('[IT-0023-AC4] returns view definitions and routine signatures', async () => {
    const viewRef: ObjectRef = { database, schema, name: 'order_view', type: 'view' };
    const view = await provider.metadata.getViewDefinition(handle!, viewRef);
    const routines = await provider.metadata.listRoutines(handle!, database, schema, {
      limit: 500,
    });

    expect(view).toMatchObject({ ref: viewRef });
    expect(view.definition).toContain('orders');
    expect(routines.items).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          ref: { database, schema, name: 'find_order', type: 'routine' },
          routineType: 'function',
          signature: expect.stringContaining('find_order(order_id bigint)'),
        }),
        expect.objectContaining({
          ref: { database, schema, name: 'refresh_orders', type: 'routine' },
          routineType: 'procedure',
          signature: 'refresh_orders()',
        }),
      ]),
    );
  });

  test('[IT-0023-AC5, SEC-0023-AC6] searches on the server with pagination and parameters', async () => {
    const page = await provider.metadata.searchObjects(
      handle!,
      database,
      'order',
      ['table', 'view'],
      {
        limit: 1,
      },
    );
    expect(page.items).toEqual([ordersRef]);
    expect(page.cursor).toBeDefined();

    const malicious = await provider.metadata.searchObjects(
      handle!,
      database,
      "'; DROP TABLE orders; --",
      ['table'],
    );
    expect(malicious.items).toEqual([]);
    await expect(
      provider.metadata.listObjects(handle!, schemaRef, ['table']),
    ).resolves.toBeDefined();
  });

  test('[CT-0023-AC7] returns the engine neutral metadata shape', async () => {
    const objects = await provider.metadata.listObjects(handle!, schemaRef, [
      'table',
      'view',
      'sequence',
      'routine',
    ]);

    expect(objects.items).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ database, schema, name: 'orders', type: 'table' }),
        expect.objectContaining({ database, schema, name: 'order_view', type: 'view' }),
        expect.objectContaining({
          database,
          schema,
          name: 'standalone_sequence',
          type: 'sequence',
        }),
        expect.objectContaining({ database, schema, name: 'find_order', type: 'routine' }),
      ]),
    );
  });
});
