import { describe, expect, test } from 'bun:test';
import type {
  ColumnDefinition,
  ConnectionHandle,
  TableChangeSet,
  TableDdlStatement,
} from '@myadmin/database-core';
import { PostgresqlTableDesigner } from '../src';

const handle: ConnectionHandle = { id: 'table-designer', openedAt: new Date(0) };

function createConnection(version = '16.4', failOn?: string) {
  const statements: string[] = [];
  return {
    statements,
    serverInfo: async () => ({ engine: 'postgresql' as const, version }),
    executeParameterized: async <T = unknown>(
      _handle: ConnectionHandle,
      parts: readonly string[],
      values: readonly unknown[],
    ): Promise<T> => {
      void values;
      const sql = parts.join('');
      statements.push(sql);
      if (failOn && sql.includes(failOn)) throw new Error('synthetic DDL failure');
      return (sql.includes('pg_class') ? [] : []) as T;
    },
    withTransaction: async <T>(_handle: ConnectionHandle, operation: () => Promise<T>) => {
      statements.push('BEGIN');
      try {
        const value = await operation();
        statements.push('COMMIT');
        return value;
      } catch (error) {
        statements.push('ROLLBACK');
        throw error;
      }
    },
  };
}

function createMetadata(localType = 'integer', targetType = localType) {
  return {
    describeTable: async (_handle: ConnectionHandle, ref: { name: string }) => ({
      ref: { database: 'app', schema: 'public', name: ref.name, type: 'table' as const },
      columns:
        ref.name === 'customers'
          ? [{ name: 'id', dataType: targetType, nullable: false } satisfies ColumnDefinition]
          : [
              { name: 'id', dataType: 'integer', nullable: false } satisfies ColumnDefinition,
              {
                name: 'customer_id',
                dataType: localType,
                nullable: false,
              } satisfies ColumnDefinition,
              {
                name: 'region',
                dataType: 'varchar(20)',
                nullable: false,
              } satisfies ColumnDefinition,
            ],
      indexes: [],
      constraints: [],
    }),
  };
}

const metadata = createMetadata();

describe('PostgreSQL table designer', () => {
  test('[UT-0041-AC8] compiles every catalogued PostgreSQL column type into one stable create DDL', async () => {
    const connection = createConnection();
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const types = await designer.types(handle);
    const columns = types.types.map((type, index) => ({
      name: `column_${index}`,
      dataType: type.name,
      nullable: true,
      ...(type.parameters.includes('length') ? { length: 24 } : {}),
      ...(type.parameters.includes('precision') ? { precision: 10, scale: 2 } : {}),
    }));

    const preview = await designer.preview(handle, {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'all_types', type: 'table' },
      columns,
    });

    expect(preview.destructive).toBe(false);
    const sql = preview.statements[0]?.sql ?? '';
    for (const column of columns) expect(sql).toContain(`"${column.name}"`);
    expect(columns).toHaveLength(types.types.length);
  });

  test('[UT-0041-AC1, UT-0041-AC3] compiles a provider-neutral create change set into stable DDL', async () => {
    const connection = createConnection();
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const changeSet: TableChangeSet = {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      columns: [
        {
          name: 'id',
          dataType: 'integer',
          nullable: false,
          identity: true,
          primaryKey: true,
        },
        {
          name: 'email',
          dataType: 'varchar',
          length: 120,
          nullable: false,
          default: { kind: 'literal', value: "a'b" },
          comment: 'Account email',
        },
      ],
    };

    await expect(designer.preview(handle, changeSet)).resolves.toEqual({
      operation: 'create',
      statements: [
        {
          sql: 'CREATE TABLE "public"."accounts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "email" varchar(120) NOT NULL DEFAULT \'a\'\'b\')',
        },
        { sql: 'COMMENT ON COLUMN "public"."accounts"."email" IS \'Account email\'' },
      ] satisfies readonly TableDdlStatement[],
      warnings: [],
      destructive: false,
    });
  });

  test('[UT-0041-AC5] returns field-level validation for unsupported identity and invalid defaults', async () => {
    const connection = createConnection('9.6.24');
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const invalid: TableChangeSet = {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'bad_table', type: 'table' },
      columns: [
        {
          name: 'enabled',
          dataType: 'boolean',
          nullable: true,
          identity: true,
          default: { kind: 'literal', value: 'maybe' },
        },
      ],
    };

    await expect(designer.preview(handle, invalid)).rejects.toMatchObject({
      issues: expect.arrayContaining([
        expect.objectContaining({ path: 'columns[0].identity', code: 'unsupported' }),
        expect.objectContaining({ path: 'columns[0].default', code: 'incompatible_default' }),
      ]),
    });
  });

  test('[UT-0041-AC2] normalizes described varchar types when altering nullability', async () => {
    const connection = createConnection();
    const described = {
      ...metadata,
      describeTable: async () => ({
        ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' as const },
        columns: [{ name: 'email', dataType: 'character varying(120)', nullable: true }],
        indexes: [],
        constraints: [],
      }),
    };
    const designer = new PostgresqlTableDesigner(connection as never, described as never);

    const preview = await designer.preview(handle, {
      operation: 'alter',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      alterations: [{ kind: 'modify', name: 'email', changes: { nullable: false } }],
    });
    expect(preview.statements).toEqual([
      { sql: 'ALTER TABLE "public"."accounts" ALTER COLUMN "email" SET NOT NULL' },
    ]);
  });

  test('[UT-0041-AC3] uses a transaction and rolls back at the failing statement', async () => {
    const connection = createConnection('16.4', 'COMMENT ON COLUMN');
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const changeSet: TableChangeSet = {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      columns: [{ name: 'email', dataType: 'text', nullable: true, comment: 'will fail' }],
    };

    await expect(designer.apply(handle, changeSet)).rejects.toMatchObject({
      statementIndex: 1,
      result: expect.objectContaining({ transactional: true, committed: false }),
    });
    expect(connection.statements).toEqual([
      expect.stringContaining('pg_class'),
      'BEGIN',
      expect.stringContaining('CREATE TABLE'),
      expect.stringContaining('COMMENT ON COLUMN'),
      'ROLLBACK',
    ]);
    expect(connection.statements).not.toContain('COMMIT');
  });

  test('[UT-0042-AC1, UT-0042-AC2, UT-0042-AC3, UT-0042-AC5, UT-0042-AC8] compiles composite indexes and every supported constraint with FK rules', async () => {
    const connection = createConnection();
    const designer = new PostgresqlTableDesigner(connection as never, createMetadata() as never);
    const preview = await designer.preview(handle, {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      columns: [
        { name: 'id', dataType: 'integer', nullable: false },
        { name: 'customer_id', dataType: 'integer', nullable: false },
        { name: 'region', dataType: 'varchar', length: 20, nullable: false },
      ],
      indexes: [{ name: 'accounts_region_customer_idx', columns: ['region', 'customer_id'] }],
      constraints: [
        { type: 'primaryKey', name: 'accounts_pk', columns: ['id', 'customer_id'] },
        { type: 'unique', name: 'accounts_region_uq', columns: ['customer_id', 'region'] },
        {
          type: 'foreignKey',
          name: 'accounts_customer_fk',
          columns: ['customer_id'],
          referencedTable: { database: 'app', schema: 'public', name: 'customers', type: 'table' },
          referencedColumns: ['id'],
          onDelete: 'CASCADE',
          onUpdate: 'RESTRICT',
        },
        { type: 'check', name: 'accounts_customer_check', expression: 'customer_id > 0' },
      ],
    });

    expect(preview.statements).toEqual([
      {
        sql: 'CREATE TABLE "public"."accounts" ("id" integer NOT NULL, "customer_id" integer NOT NULL, "region" varchar(20) NOT NULL, CONSTRAINT "accounts_pk" PRIMARY KEY ("id", "customer_id"), CONSTRAINT "accounts_region_uq" UNIQUE ("customer_id", "region"), CONSTRAINT "accounts_customer_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT "accounts_customer_check" CHECK (customer_id > 0))',
      },
      {
        sql: 'CREATE INDEX "accounts_region_customer_idx" ON "public"."accounts" ("region", "customer_id")',
      },
    ]);
  });

  test('[UT-0042-AC4, UT-0042-AC7, UT-0042-AC8] reports destructive index and PK/FK drops and rejects incompatible FK types', async () => {
    const connection = createConnection();
    const described = {
      describeTable: async (_handle: ConnectionHandle, ref: { name: string }) => ({
        ref: { database: 'app', schema: 'public', name: ref.name, type: 'table' as const },
        columns: [
          { name: 'id', dataType: 'integer', nullable: false } satisfies ColumnDefinition,
          { name: 'customer_id', dataType: 'integer', nullable: false } satisfies ColumnDefinition,
        ],
        indexes: [{ name: 'lookup_idx', columns: ['customer_id'], unique: false, primary: false }],
        constraints: [
          { name: 'accounts_pk', type: 'primaryKey', columns: ['id'] },
          { name: 'accounts_fk', type: 'foreignKey', columns: ['customer_id'] },
        ],
      }),
    };
    const designer = new PostgresqlTableDesigner(connection as never, described as never);
    const preview = await designer.preview(handle, {
      operation: 'alter',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      alterations: [
        { kind: 'dropIndex', name: 'lookup_idx' },
        { kind: 'dropConstraint', name: 'accounts_pk' },
        { kind: 'dropConstraint', name: 'accounts_fk' },
      ],
    });
    expect(preview).toMatchObject({
      destructive: true,
      statements: [
        { destructiveIndexes: ['lookup_idx'] },
        {
          destructiveConstraints: ['accounts_pk'],
          warning: expect.stringContaining('row identity'),
        },
        {
          destructiveConstraints: ['accounts_fk'],
          warning: expect.stringContaining('relational integrity'),
        },
      ],
    });

    const incompatible = new PostgresqlTableDesigner(
      connection as never,
      createMetadata('integer', 'bigint') as never,
    );
    await expect(
      incompatible.preview(handle, {
        operation: 'alter',
        ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
        alterations: [
          {
            kind: 'addConstraint',
            constraint: {
              type: 'foreignKey',
              name: 'bad_fk',
              columns: ['customer_id'],
              referencedTable: {
                database: 'app',
                schema: 'public',
                name: 'customers',
                type: 'table',
              },
              referencedColumns: ['id'],
            },
          },
        ],
      }),
    ).rejects.toMatchObject({
      issues: [expect.objectContaining({ code: 'incompatible_type' })],
    });
  });
});
