import { describe, expect, test } from 'bun:test';
import type {
  ColumnDefinition,
  ConnectionHandle,
  TableChangeSet,
  TableDdlStatement,
} from '@myadmin/database-core';
import { PostgresqlTableDesigner } from '../src';

const handle: ConnectionHandle = { id: 'table-designer', openedAt: new Date(0) };

function createConnection(version = '16.4', failOn?: string) {
  const statements: string[] = [];
  return {
    statements,
    serverInfo: async () => ({ engine: 'postgresql' as const, version }),
    executeParameterized: async <T = unknown>(
      _handle: ConnectionHandle,
      parts: readonly string[],
      values: readonly unknown[],
    ): Promise<T> => {
      void values;
      const sql = parts.join('');
      statements.push(sql);
      if (failOn && sql.includes(failOn)) throw new Error('synthetic DDL failure');
      return (sql.includes('pg_class') ? [] : []) as T;
    },
  };
}

const metadata = {
  describeTable: async () => ({
    ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' as const },
    columns: [
      {
        name: 'id',
        dataType: 'integer',
        nullable: false,
        isIdentity: true,
      } satisfies ColumnDefinition,
    ],
    indexes: [],
    constraints: [],
  }),
};

describe('PostgreSQL table designer', () => {
  test('compiles a provider-neutral create change set into stable DDL', async () => {
    const connection = createConnection();
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const changeSet: TableChangeSet = {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      columns: [
        {
          name: 'id',
          dataType: 'integer',
          nullable: false,
          identity: true,
          primaryKey: true,
        },
        {
          name: 'email',
          dataType: 'varchar',
          length: 120,
          nullable: false,
          default: { kind: 'literal', value: "a'b" },
          comment: 'Account email',
        },
      ],
    };

    await expect(designer.preview(handle, changeSet)).resolves.toEqual({
      operation: 'create',
      statements: [
        {
          sql: 'CREATE TABLE "public"."accounts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, "email" varchar(120) NOT NULL DEFAULT \'a\'\'b\')',
        },
        { sql: 'COMMENT ON COLUMN "public"."accounts"."email" IS \'Account email\'' },
      ] satisfies readonly TableDdlStatement[],
      warnings: [],
      destructive: false,
    });
  });

  test('returns field-level validation for unsupported identity and invalid defaults', async () => {
    const connection = createConnection('9.6.24');
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const invalid: TableChangeSet = {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'bad_table', type: 'table' },
      columns: [
        {
          name: 'enabled',
          dataType: 'boolean',
          nullable: true,
          identity: true,
          default: { kind: 'literal', value: 'maybe' },
        },
      ],
    };

    await expect(designer.preview(handle, invalid)).rejects.toMatchObject({
      issues: expect.arrayContaining([
        expect.objectContaining({ path: 'columns[0].identity', code: 'unsupported' }),
        expect.objectContaining({ path: 'columns[0].default', code: 'incompatible_default' }),
      ]),
    });
  });

  test('normalizes described varchar types when altering nullability', async () => {
    const connection = createConnection();
    const described = {
      ...metadata,
      describeTable: async () => ({
        ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' as const },
        columns: [{ name: 'email', dataType: 'character varying(120)', nullable: true }],
        indexes: [],
        constraints: [],
      }),
    };
    const designer = new PostgresqlTableDesigner(connection as never, described as never);

    const preview = await designer.preview(handle, {
      operation: 'alter',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      alterations: [{ kind: 'modify', name: 'email', changes: { nullable: false } }],
    });
    expect(preview.statements).toEqual([
      { sql: 'ALTER TABLE "public"."accounts" ALTER COLUMN "email" SET NOT NULL' },
    ]);
  });

  test('uses a transaction and rolls back at the failing statement', async () => {
    const connection = createConnection('16.4', 'COMMENT ON COLUMN');
    const designer = new PostgresqlTableDesigner(connection as never, metadata as never);
    const changeSet: TableChangeSet = {
      operation: 'create',
      ref: { database: 'app', schema: 'public', name: 'accounts', type: 'table' },
      columns: [{ name: 'email', dataType: 'text', nullable: true, comment: 'will fail' }],
    };

    await expect(designer.apply(handle, changeSet)).rejects.toMatchObject({
      statementIndex: 1,
      result: expect.objectContaining({ transactional: true, committed: false }),
    });
    expect(connection.statements).toEqual([
      expect.stringContaining('pg_class'),
      'BEGIN',
      expect.stringContaining('CREATE TABLE'),
      expect.stringContaining('COMMENT ON COLUMN'),
      'ROLLBACK',
    ]);
    expect(connection.statements).not.toContain('COMMIT');
  });
});
